export const character_data = [
	"John, Smith, Maverick, male",
	"Emily, Davis, Sparkle, female",
	"Alex, Johnson, Innovator, non-binary",
	"Sarah, Williams, Sunshine, female",
	"Michael, Brown, Explorer, male",
	"Taylor, Anderson, Trailblazer, non-binary",
	"Jessica, Lee, Dreamer, female",
	"David, Martinez, Techie, male",
	"Emma, Taylor, Enigma, female",
	"Ryan, Robinson, Visionary, male",
	"Taylor, Clark, Catalyst, non-binary",
	"Olivia, Turner, Melody, female",
	"Jordan, White, Whiz, non-binary",
	"Matthew, King, Genius, male",
	"Sophia, Garcia, Luminary, female",
	"Avery, Wright, Voyager, non-binary",
	"Lily, Moore, Serenity, female",
	"Ethan, Parker, Innovator, male",
	"Harper, Hall, Spark, non-binary",
	"Benjamin, Lewis, Scholar, male",
	"Mia, Adams, Harmony, female",
	"Riley, Wilson, Pioneer, non-binary",
	"Chloe, Harris, Artist, female",
	"Mason, Carter, Maestro, male",
	"Kim Isak, Olsen, Kimmi, male",
];